backend:
  name: github
  repo: eliaslep-stack/ildigitalassistant-site
  branch: main
  base_url: https://oauth.ildigitalassistant.com
  auth_endpoint: /callback

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
